public without sharing class Constants {
	// Pet constants
	public static final String PET_RT_NAME_DOG = 'Dog';
	public static final String PET_STATUS_CREATED = 'Created';
	public static final String PET_STATUS_REGISTERED = 'RegisteredAvailable';
	public static final String PET_STATUS_IN_ADOPTION = 'InAdoptionProcess';
	public static final String PET_STATUS_ADOPTED = 'Adopted';

	// Adoption Request constants
	public static final String REQUEST_STATUS_CREATED = 'Created';
	public static final String REQUEST_STATUS_APPROVED = 'Approved';
	public static final String REQUEST_STATUS_ADOPTED = 'CompletedAdopted';
	public static final String REQUEST_STATUS_NOT_ADOPTED = 'CompletedNotAdopted';

	// Case constants
	public static final String CASE_STATUS_CLOSED = 'Closed';
}